<a href="https://colab.research.google.com/github/zamman365-glitch/Statistics/blob/main/Z_Test_%26_P_Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [79]:
import numpy as np

In [80]:
data = [52,48,51,49,50,52,51,54,50]

In [81]:
# Known Population mean
population_men = 50 #(u)

In [82]:
# know population std. deviation
population_std = 5

In [83]:
# Sample mean ]
sample_men = np.mean(data)

In [84]:
# significance level
alpha = 0.5

In [85]:
z_score = (sample_men - population_men) / (population_std / np.sqrt(len(data)))

In [86]:
z_score

np.float64(0.4666666666666671)

In [87]:
from scipy.stats import norm
p_value = 2*(1-norm.cdf(abs(z_score)))
#normal distridution(norm)
#comulative distribution function

In [88]:
p_value

np.float64(0.6407383818025405)

In [89]:
if p_value<alpha:
  print("Reject the null hypothesis")
else:
  print("Fail to reject the null hypothesis")

Fail to reject the null hypothesis

In [90]:
72-75

-3

In [91]:
np.sqrt(40)

np.float64(6.324555320336759)

In [92]:
10/6.32

1.5822784810126582

In [93]:
print(-3/1.58)

-1.8987341772151898

In [94]:
if 1.89 < 1.64:
  print("reject the null hypothesis")
else:
  print("fail to reject the null hypothesis ")

fail to reject the null hypothesis

In [95]:
145-150

-5

In [96]:
np.sqrt(10)

np.float64(3.1622776601683795)

In [97]:
8/3.16

2.531645569620253

In [98]:
-5/2.53

-1.9762845849802373

In [99]:
d = 1.833

In [100]:
20 - 18.5

1.5

In [101]:
np.sqrt(15)

np.float64(3.872983346207417)

In [102]:
3.2/3.87

0.82687338501292

In [103]:
1.5 / 0.82

1.829268292682927

In [104]:
#T - test

In [105]:
from scipy.stats import ttest_1samp

In [106]:
# sample data
data = [145,148,142,150,144,147,143,145,149,141]

In [107]:
# Population mean
population_mean = 150

In [108]:
t_value, p_values = ttest_1samp(data,population_mean)

In [109]:
t_value

np.float64(-4.807457798612156)

In [110]:
p_values

np.float64(0.0009636544129761595)

In [111]:
if p_values < 0.05:
  print("Reject the null hypothesis")
else:
  print("Fail to reject the null hypothesis")

Reject the null hypothesis

In [112]:
import seaborn as sns

In [113]:
df=sns.load_dataset("titanic")

In [114]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [115]:
import pandas as pd
contigency_table=pd.crosstab(df["class"],df["survived"])

In [116]:
contigency_table

survived    0    1
class
First      80  136
Second     97   87
Third     372  119

In [117]:
from scipy.stats import chi2_contingency

In [118]:
chi2,p,dof,expected=chi2_contingency(contigency_table)

In [119]:
dof

2

In [120]:
p

np.float64(4.549251711298793e-23)

In [121]:
print(chi2)
print(p)
print(dof)
print(expected)

102.88898875696056
4.549251711298793e-23
2
[[133.09090909  82.90909091]
 [113.37373737  70.62626263]
 [302.53535354 188.46464646]]

In [122]:
if chi2 > p:
  print("Reject the null hypothesis")
else:
  print("Fail to reject the null hypothesis")

Reject the null hypothesis

In [118]:
#ANNOVA(analysis of variance):- we use annova test when we have to compare two samples on the basis of thier mean

In [ ]:
# we have SSB and SSW

In [ ]:
import numpy as np

In [ ]:
fertilizer_A=[20,22,19,21,23]
fertilizer_B=[25,27,24,26,28]
fertilizer_C=[30,32,29,31,33]